services:

  nginx:
    build:
      args:
        NODE_PROJET: ${NODE_PROJET}
        FRONTEND_PATH: ${FRONTEND_PATH}
      context: container/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - backend
      - frontend
    environment:
      NODE_PROJET: ${NODE_PROJET}
      FRONTEND_PATH: ${FRONTEND_PATH}
    ports:
      - "3000:443"
      - "7000:7000"
    volumes:
      - backend_data:${BACKEND_PATH}
      - frontend_data:${FRONTEND_PATH}
      - data:/etc/nginx/ssl
    restart: always
    networks:
      - iron_network

  backend:
    build:
      context: container/backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - NODE_PROJET=${NODE_PROJET}
    volumes:
      - backend_data:${BACKEND_PATH}
    working_dir: ${BACKEND_PATH}
    ports:
      - "7000"
    restart: always
    networks:
      - iron_network

  frontend:
    build:
      context: container/frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NODE_PROJET=${NODE_PROJET}
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - frontend_data:${FRONTEND_PATH}
    working_dir: ${FRONTEND_PATH}
    ports:
      - "3000"
    restart: on-failure
    networks:
      - iron_network

  # mariadb:
  #   build:
  #     context: container/mariadb
  #     dockerfile: Dockerfile
  #   container_name: mariadb
  #   volumes:
  #     - sqlite_data:/var/lib/mysql
  #   ports:
  #     - "3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #   restart: always
  #   networks:
  #     - iron_network

  # phpmyadmin:
  #   image: phpmyadmin
  #   container_name: phpmyadmin
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: mariadb
  #     PMA_USER: ${MYSQL_USER}
  #     PMA_PASSWORD: ${MYSQL_PASSWORD}
  #     PMA_PORT: 3306
  #   restart: always
  #   networks:
  #     - iron_network

  # sqlitebrowser:
  #   image: linuxserver/sqlitebrowser
  #   container_name: sqlitebrowser
  #   volumes:
  #     - sqlite_data:/var/lib/sqlite
  #   ports:
  #     - "127.0.0.1:3001:3001"
  #   depends_on:
  #     - backend
  #   restart: always
  #   networks:
  #   - iron_network

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}
      o: bind
  backend_data:
    driver: local
    driver_opts:
      type: none
      device: ${BACKEND_PATH}
      o: bind
  frontend_data:
    driver: local
    driver_opts:
      type: none
      device: ${FRONTEND_PATH}
      o: bind

networks:
  iron_network:
    driver: bridge
